### ISSUE TITLE
Plantear viabilidad económica

### ISSUE THREAD

**Issue by Alberto-Vivar** [Alberto-Vivar/3D-Viewer#169]
Coste hipotético, amortizaciones, venta, modelos de negocio, etc.

**Comment by alvarag** [comment]
Coloco aquí las correcciones de la memoria:

[anexosC.pdf](https://github.com/Alberto-Vivar/3D-Viewer/files/1051744/anexosC.pdf)
[memoriaC.pdf](https://github.com/Alberto-Vivar/3D-Viewer/files/1051745/memoriaC.pdf)

Revisa en los anexos las comillas, que es mejor utilizar las latinas como ya haces en otros sitios << y >>

**Comment by Alberto-Vivar** [comment]
¿A qué departamento y área pertenecéis, @alvarag @joseFranciscoDiez?
Así os pongo correctamente en la memoria.
En cada sitio que busco me aparece una cosa.
:confused:

**Comment by alvarag** [comment]
Somos del departamento de ingeniería civil, área de lenguajes y sistemas informáticos.
