### ISSUE TITLE
Añadir capturas a manual usuario

### ISSUE THREAD

**Issue by Alberto-Vivar** [Alberto-Vivar/3D-Viewer#176]

**Comment by alvarag** [comment]
Comentarios de la versión actual de la documentación:
[anexosC.pdf](https://github.com/Alberto-Vivar/3D-Viewer/files/1084625/anexosC.pdf)
[memoriaC.pdf](https://github.com/Alberto-Vivar/3D-Viewer/files/1084626/memoriaC.pdf)

**Comment by Alberto-Vivar** [comment]
La lista de código ya consigo hacerla flotante, pero no se cómo hacer que los diagramas de clases aparezcan ellos solos sin explicaciones entre medias (como el texto cabe, al final entra).

¿Cómo se haría?

**Comment by alvarag** [comment]
LaTeX tiene una serie de algoritmos de maquetación bastante sofisticados que hace que no tengamos que preocuparnos por la estética del documento. Si no pones colocadores en las tablas y figuras (cosas como [h] o [t]), él lo colocará donde "crea" que mejor queda.
