### ISSUE TITLE
Documentar el proceso de eliminación de puntos de los modelos

### ISSUE THREAD

**Issue by joseFranciscoDiez** [Alberto-Vivar/3D-Viewer#178]
Saludos

Mañana voy a instalarle a Rebeca el visor, estaría bien tener un recordatorio de como se eliminan los puntos superfluos de los modelos.
Si no te da tiempo a cambiar el anexo del programador puedes ponerme los comandos en esta issue.

**Comment by Alberto-Vivar** [comment]
Espero que te sirva, comenta con lo que sea. Reábrelo si ves algún problema.
