### ISSUE TITLE
Reunión martes 13 de diciembre con el cliente.

### ISSUE THREAD

**Issue by joseFranciscoDiez** [Alberto-Vivar/3D-Viewer#19]
El pasado martes 13 de diciembre se hizo una reunión con el cliente (Rebeca García, profesora del Master en evolución humana).

Se le enseñó el visor y las funciónes que actualmente estaban implementadas y se discutió sobre el uso que se le podría dar. Se identificaron los siguientes casos de uso.

Rol Profesor
  

-  Publicar lección: Se publica un modelo junto con unas anotaciones. El profesor elige un modelo, coloca en el modelo anotaciones y las añade un texto con un text input. 

- Publicar ejercicio: Se publica un modelo junto con una tarea que hay que hacer sobre este. Hay dos tipos de tarea:
   1. Identificación y localización. El alumno tiene que saber de que hueso se trata y debe ser capaz de colocar en el modelo una serie de puntos identificativos eligiendo los nombre de estos puntos de una lista desplegable. La lista va a ser diferente para cada hueso así que si el alumno se equivoca de hueso va a estar todo mal.
    2. Medidas autocalculadas. Se le pide al alumno que calcule una determinada medida. Las medidas son autocalculadas luego el alumno solo tiene que colocar en el modelo las anotaciones de los puntos identificativos que intervienen en ese calculo.

- Cargar ejercicios para su corrección: La resolución de un ejercicio produce un fichero. El profesor puede cargar ese fichero y ver lo que ha hecho el alumno. La corrección es manual. Se puede plantear la correción automática para algún caso sencillo de medidas autocalculadas.

- Detección de copia (opcional) : Si se cargan todos los ficheros de ejercicios de alumnos, el programa puede detectar aquellos que sean demasiado similares (las anotaciones estén colocadas en el mismo sitio con una precisión demasiado sospechosa)

Rol alumno:
- Abrir lección. Se carga el modelo y las anotaciones asignadas a dicho modelo. El alumno mueve, rota y manipula el modelo en el espacio.
- Realizar ejercicio. Se carga el ejercicio, junto un enunciado. El alumno coloca las anotaciones. Salva el ejercicio (abría que decidir si guarda cada ejercicio o todo el cuestionario en el mismo fichero). Se produce un fichero que es el entregable de esta tarea.

**Comment by Alberto-Vivar** [comment]
Estas últimas dependencias sirven para crear un sistema antiplagio.
