### ISSUE TITLE
Más comentarios sobre la memoria y anexos

### ISSUE THREAD

**Issue by joseFranciscoDiez** [Alberto-Vivar/3D-Viewer#202]
[anexosVisor2.pdf](https://github.com/Alberto-Vivar/3D-Viewer/files/1097688/anexosVisor2.pdf)
[memoriaVisor2.pdf](https://github.com/Alberto-Vivar/3D-Viewer/files/1097689/memoriaVisor2.pdf)

**Comment by Alberto-Vivar** [comment]
@joseFranciscoDiez 
En una corrección de la memoria, mencionas que una herramienta utilizada es el editor de latex. ¿No hablamos en una reunión que las herramientas básicas y comunes, como el editor de textos, un navegador web, etc no se incluían?

**Comment by Alberto-Vivar** [comment]
@joseFranciscoDiez 
Respecto a los anexos:
> va a haber una cuenta invitado predefinida (login: invitado pass:invitado) que permita entrar a ver la aplicación ?

¿Debería haberla?
Entonces habría que modificar código.
¿Con qué utilidad? >> Los miembros del tribunal ya pueden acceder.

**Comment by joseFranciscoDiez** [comment]
- El editor de latex es una herramienta que puedes mencionar, aunque no es algo tan prioritario como el resto de herramientas.

- Me refiero a que tendría que haber una sección explicando el formato STL, en el sentido de explicar su nombre, su origen, sus usos más habituales y sus diferencias con PLY, algo que no debería ser más de 3-4 líneas

 - ¿Con qué utilidad? >> Los miembros del tribunal ya pueden acceder.
¿Como acceden los miembros del tribunal, solo con su login y pass de ubivirtual?

**Comment by Alberto-Vivar** [comment]
> * ¿Con qué utilidad? >> Los miembros del tribunal ya pueden acceder.
¿Como acceden los miembros del tribunal, solo con su login y pass de UBUVirtual?

En efecto, los miembros del tribunal pueden acceder igual que tu, que alvar o que yo, con su email y pass de ubuvirtual. Fue una mejora introducida en 785ff5104e8212693f6cc80a3cf9fbcf9d54970f.
Estamos permitidos todos nosotros, y con el modo normal del servidor (no el debug, que hay que activar), el login se realiza contra la API de UBUVirtual.
